version: '3.8'

services:
  servermanager-api:
    build: 
      context: ./
      dockerfile: ServerManagerApi/dockerfile
    ports:
      - "5000:5000"

  regenmeter-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
