version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - appnetwork
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=YourDatabase;User Id=sa;Password=YourStrong!Passw0rd;

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - appnetwork
    volumes:
      - sql_data:/var/opt/mssql

networks:
  appnetwork:

volumes:
  sql_data:
