# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build, test, and coverage

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ServerManager/ServerManagerApi/ServerManager.sln

    - name: Build
      run: dotnet build ServerManager/ServerManagerApi/ServerManagerApi/ServerManagerApi.csproj --no-restore

    - name: Test with code coverage
      run: |
        dotnet test ServerManager/ServerManagerApi/ServerManagerTests/ServerManagerTests.csproj \
          --verbosity normal \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover
      continue-on-error: true

    - name: Generate coverage report
      if: ${{ always() }}
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator \
          -reports:"**/coverage.opencover.xml" \
          -targetdir:"coverage-report" \
          -reporttypes:"Html"

    - name: Upload coverage artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage-report
